title: Pasión de animales
description:  Aquí veras diferentes animales
permalink: ':title/'
baseurl: "/" 
url: "https://Pasiondeanimales.github.io" 
site-twitter: 


author: Pasión de animales  
author-img: focas.jpg
about-author: En este blog es para que veas y para q sepas cosas sobre los animales
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
